# Generated by Django 5.2.1 on 2025-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ejecución')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Detalle de Reparación',
                'verbose_name_plural': 'Detalles de Reparación',
                'ordering': ['fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Reparación',
                'verbose_name_plural': 'Historial de Estados de Reparaciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('descripcion_problema', models.TextField(verbose_name='Descripción del Problema')),
                ('descripcion_solucion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Solución')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Total')),
            ],
            options={
                'verbose_name': 'Reparación',
                'verbose_name_plural': 'Reparaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('duracion_estimada', models.DurationField(verbose_name='Duración Estimada')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
