# Generated by Django 5.2.1 on 2025-05-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0001_initial'),
        ('reparaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialestadoreparacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado', verbose_name='Técnico Asignado'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carros.carro', verbose_name='Vehículo'),
        ),
        migrations.AddField(
            model_name='historialestadoreparacion',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='reparaciones.reparacion'),
        ),
        migrations.AddField(
            model_name='detallereparacion',
            name='reparacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.reparacion', verbose_name='Reparación'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='servicios',
            field=models.ManyToManyField(through='reparaciones.DetalleReparacion', to='reparaciones.servicio', verbose_name='Servicios'),
        ),
        migrations.AddField(
            model_name='detallereparacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reparaciones.servicio', verbose_name='Servicio'),
        ),
    ]
