# Generated by Django 5.2.1 on 2025-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='combustible',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('diesel', 'Diesel'), ('electrico', 'Eléctrico'), ('hibrido', 'Híbrido')], default='gasolina', max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carro',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado'), ('recondicionado', 'Recondicionado')], default='usado', max_length=50),
        ),
        migrations.AlterField(
            model_name='carro',
            name='imagen_principal',
            field=models.ImageField(blank=True, default='carros/default_car.png', null=True, upload_to='carros/'),
        ),
        migrations.AlterField(
            model_name='carro',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='transmision',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática'), ('semiautomatica', 'Semiautomática')], default='manual', max_length=50),
        ),
    ]
