# Generated by Django 5.2.1 on 2025-05-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='preferencias',
            field=models.TextField(blank=True, default='Sin preferencias registradas', null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(default='Empleado General', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='especialidad',
            field=models.CharField(blank=True, default='Sin especialidad registrada', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.TextField(blank=True, default='Sin dirección registrada', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default_profile.png', null=True, upload_to='perfiles/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
