# Generated by Django 5.2.1 on 2025-05-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piezas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariopieza',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_piezas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pieza',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piezas.categoriapieza', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='comentariopieza',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='piezas.pieza'),
        ),
    ]
