# Generated by Django 5.2.1 on 2025-05-29 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piezas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriapieza',
            name='descripcion',
            field=models.TextField(blank=True, default='Categoría de piezas', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='categoriapieza',
            name='imagen',
            field=models.ImageField(blank=True, default='categorias_piezas/default_category.png', null=True, upload_to='categorias_piezas/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='comentariopieza',
            name='calificacion',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='comentariopieza',
            name='contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piezas.categoriapieza', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='compatibilidad',
            field=models.TextField(blank=True, default='Compatible con la mayoría de modelos', null=True, verbose_name='Compatibilidad con Modelos'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='garantia',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Garantía (meses)'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='imagen',
            field=models.ImageField(blank=True, default='piezas/default_piece.png', null=True, upload_to='piezas/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='pieza',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
