# Generated by Django 5.2.1 on 2025-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('VEHICULO', 'Vehículo'), ('SERVICIO', 'Servicio')], max_length=20, verbose_name='Tipo')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_devoluciones/', verbose_name='Archivo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Documento de Devolución',
                'verbose_name_plural': 'Documentos de Devoluciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Devolución',
                'verbose_name_plural': 'Historial de Estados de Devoluciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
