# Generated by Django 5.2.1 on 2025-05-29 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carros', '0001_initial'),
        ('devoluciones', '0001_initial'),
        ('piezas', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='producto_devuelto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='piezas.pieza', verbose_name='Producto Devuelto'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='vehiculo_devuelto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carros.carro', verbose_name='Vehículo Devuelto'),
        ),
        migrations.AddField(
            model_name='documentodevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='devoluciones.devolucion'),
        ),
        migrations.AddField(
            model_name='historialestadodevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='devoluciones.devolucion'),
        ),
        migrations.AddField(
            model_name='historialestadodevolucion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
