# Generated by Django 5.2.1 on 2025-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROGRAMADA', 'Programada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_programada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Programada')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('duracion_real', models.DurationField(blank=True, null=True, verbose_name='Duración Real')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('resultado', models.TextField(blank=True, null=True, verbose_name='Resultado')),
                ('calificacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calificación')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
            ],
            options={
                'verbose_name': 'Asesoría',
                'verbose_name_plural': 'Asesorías',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TipoAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('duracion_estimada', models.DurationField(verbose_name='Duración Estimada')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Tipo de Asesoría',
                'verbose_name_plural': 'Tipos de Asesorías',
                'ordering': ['nombre'],
            },
        ),
    ]
