# Generated by Django 5.2.1 on 2025-05-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asesorias', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado', verbose_name='Asesor'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='tipo_asesoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asesorias.tipoasesoria', verbose_name='Tipo de Asesoría'),
        ),
    ]
