import { Wrench, PenToolIcon as Tool, ShoppingCart } from 'lucide-react';

export const cars = [
  {
    id: '1',
    brand: 'Chevrolet',
    model: 'Bel Air',
    year: 1957,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 6500,
    priceCUP: null,
    image: 'https://bringatrailer.com/wp-content/uploads/2017/10/IMG_0124_5_6.jpg',
    isNew: false,
  },
  {
    id: '2',
    brand: 'Dodge',
    model: 'Coronet',
    year: 1956,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 13000,
    priceCUP: null,
    image: 'https://media.gettyimages.com/id/1181829222/photo/1969-dodge-coronet-r-t-440-creator-unknown.jpg?b=1&s=594x594&w=0&k=20&c=dnx8js51FB8t20UO2KG4V0Q3Pb8Al6vwaxf65YeCjyw=',
    isNew: false,
  },
  {
    id: '3',
    brand: 'Willys',
    model: 'Jeep',
    year: 1948,
    mileage: null,
    fuel: 'Diésel',
    priceMLC: 9000,
    priceCUP: null,
    image: 'https://c1.staticflickr.com/9/8231/8430122295_f8309ce6b1_b.jpg',
    isNew: false,
  },
  {
    id: '4',
    brand: 'Polski Fiat',
    model: '126p',
    year: 1970,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 2500,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.a03287b9f9b3d3bbc462e5948ddd6076?rik=9BADjnl1CUuULw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '5',
    brand: 'Lada',
    model: '2107',
    year: 2006,
    mileage: 69000,
    fuel: 'Gasolina',
    priceMLC: 14500,
    priceCUP: null,
    image: 'https://bringatrailer.com/wp-content/uploads/2021/10/1989_lada_2107_163721200466a8f55ba309b7c03E7F317D-53FC-4B4C-B851-87645B9374F0.jpeg',
    isNew: false,
  },
  {
    id: '6',
    brand: 'Moskvich',
    model: 'Aleko',
    year: 1990,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 5000,
    priceCUP: null,
    image: 'https://i.pinimg.com/736x/33/83/64/338364866882903838b4e8ff549bb22d--bulgaria-photos.jpg',
    isNew: false,
  },
  {
    id: '7',
    brand: 'Volkswagen',
    model: 'Combi',
    year: 1978,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 8000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.91aae40741087475eecd74acbd911370?rik=z1eOBGOZcDxYEA&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '8',
    brand: 'Chevrolet',
    model: 'Chevette',
    year: 1980,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 7000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.e879b06201bf3dd049a44a1b7ab0201c?rik=MDQdqjZKWEJC%2fw&riu=http%3a%2f%2fwww.roadsmile.com%2fimages%2fchevrolet-chevette_blue_7.jpg&ehk=oav088BbP6utDAd5AnlH5JhFGljQWgkIaneZzaFt3BU%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '9',
    brand: 'Fiat',
    model: 'Uno',
    year: 1983,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 7200,
    priceCUP: null,
    image: 'https://drive-my.com/wp-content/uploads/importedmedia/824-scaled.jpg',
    isNew: false,
  },
  {
    id: '10',
    brand: 'Yugo',
    model: 'GV',
    year: 1988,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 4000,
    priceCUP: null,
    image: 'https://barnfinds.com/wp-content/uploads/2019/03/1988-Yugo-GV-1.jpg',
    isNew: false,
  },
  {
    id: '11',
    brand: 'Renault',
    model: '12',
    year: 1972,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 5500,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.344eed4eb7cbbd32312f376639c57570?rik=fhuqBMqU1d6K3A&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '12',
    brand: 'Ford',
    model: 'Mustang',
    year: 1965,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 20000,
    priceCUP: null,
    image: 'https://bringatrailer.com/wp-content/uploads/2019/01/1965_ford_mustang_1548437373c7484d581965_ford_mustang_154826812137ba7d308fcIMG_8170-1.jpg',
    isNew: false,
  },
  {
    id: '13',
    brand: 'Cadillac',
    model: 'Fleetwood',
    year: 1959,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 15000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.9077017245f70c85574ad4b77207483c?rik=U8KV5U7ZKlQK2Q&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '14',
    brand: 'Buick',
    model: 'Special',
    year: 1954,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 8000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.2604a8a3e331e407daafe606d578b93c?rik=fqQH4vCpNwaN5A&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '15',
    brand: 'Oldsmobile',
    model: '88',
    year: 1953,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 9000,
    priceCUP: null,
    image: 'https://bringatrailer.com/wp-content/uploads/2023/07/1953_oldsmobile_super-88_photo-jun-17-2023-5-23-34-pm-17423.jpg',
    isNew: false,
  },
  {
    id: '16',
    brand: 'Chevrolet',
    model: 'Camaro',
    year: 1969,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 18000,
    priceCUP: null,
    image: 'https://res.cloudinary.com/mecum/image/upload/v1669823128/auctions/sc19/sc0519-371395/1022046_1.jpg',
    isNew: false,
  },
  {
    id: '17',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2018,
    mileage: 70000,
    fuel: 'Gasolina',
    priceMLC: 22000,
    priceCUP: null,
    image: 'https://media.ed.edmunds-media.com/toyota/corolla/2018/oem/2018_toyota_corolla_sedan_le-eco-wpremium-package_fq_oem_2_1280.jpg',
    isNew: false,
  },
  {
    id: '18',
    brand: 'Kia',
    model: 'Picanto',
    year: 2020,
    mileage: 30000,
    fuel: 'Gasolina',
    priceMLC: 30000,
    priceCUP: null,
    image: 'https://img.philkotse.com/2020/12/21/O3IWXvly/1-ad38.png',
    isNew: false,
  },
  {
    id: '19',
    brand: 'Geely',
    model: 'CK',
    year: 2010,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 23000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.a7c2c2f90ab3ef4785aa955a7a0e8994?rik=cAPnBEbN97cQIg&riu=http%3a%2f%2favatars.mds.yandex.net%2fget-verba%2f216201%2f2a000001609d6a059cda3f1120e8091f5d31%2fcattouchretcr&ehk=b6y0xRyFIYqDcKJSTGpuO%2b2xStYPcoOnSQwEd%2bdm8rs%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '20',
    brand: 'Hyundai',
    model: 'Accent',
    year: 2017,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 24000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.93e86e8c6fd2ea01ad02c77ca5d83f60?rik=9QulnxOO%2fmDuUw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '21',
    brand: 'Hyundai',
    model: 'Venue',
    year: 2021,
    mileage: 48250,
    fuel: 'Gasolina',
    priceMLC: 17000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.b13468cc76265421d76a3cc97807350e?rik=Vx9eMBlsqcVaEg&pid=ImgRaw&r=0',
    isNew: true,
  },
  {
    id: '22',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2020,
    mileage: 64200,
    fuel: 'Gasolina',
    priceMLC: 14000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.d03792212bc3028f2678fbc01bbdfeda?rik=166rEZAd9gftdg&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '23',
    brand: 'Hyundai',
    model: 'Santa Fe',
    year: 2022,
    mileage: 19650,
    fuel: 'Gasolina',
    priceMLC: 17000,
    priceCUP: null,
    image: 'https://www.kbb.com/cs-camp/wp-content/uploads/2021/07/FTM_MY22_Hyundai_SantaFe_Lifestyle_1920x1080_01.png',
    isNew: true,
  },
  {
    id: '24',
    brand: 'Kia',
    model: 'Rio',
    year: 2019,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 25000,
    priceCUP: null,
    image: 'https://gearopen.com/wp-content/uploads/2018/11/best-2019-kia-rio-spesification.jpg',
    isNew: false,
  },
  {
    id: '25',
    brand: 'Toyota',
    model: 'RAV4',
    year: 2019,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 27000,
    priceCUP: null,
    image: 'https://www.mad4wheels.com/img/free-car-images/mobile/16862/toyota-rav4-xle-awd-premium-blue-flame-2019-520760.jpg',
    isNew: false,
  },
  {
    id: '26',
    brand: 'Ford',
    model: 'Escape',
    year: 2020,
    mileage: 44300,
    fuel: 'Gasolina',
    priceMLC: 22000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.d8c182223511c106f746c43b9879701e?rik=bvImqLsYbxzFJw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '27',
    brand: 'Subaru',
    model: 'Crosstrek',
    year: 2019,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 15000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.158d7df72b883c50937977fa28a7f455?rik=UwW04Kp0FEdIKw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '28',
    brand: 'Cadillac',
    model: 'XT5',
    year: 2019,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 20000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.6e385273118bb302606afb60a5e0cfdd?rik=6JoDB9CJlpeadg&riu=http%3a%2f%2fs1.cdn.autoevolution.com%2fimages%2fgallery%2fCADILLAC-XT5-5730_44.jpg&ehk=uPknnYwiu27199GvKv%2ftABriU1VCJ0OydMq1ouSLYSk%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '29',
    brand: 'Mercedes-Benz',
    model: 'C300',
    year: 2014,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 8500,
    priceCUP: null,
    image: 'https://cdn.dealeraccelerate.com/adrenalin/1/1130/29803/1920x1440/2014-mercedes-benz-c-class-c300-sport-4matic',
    isNew: false,
  },
  {
    id: '30',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2016,
    mileage: 64400,
    fuel: 'Gasolina',
    priceMLC: 40000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.1485b50f45ddcf961f509f65a7190cd4?rik=2LbourikPw6Etw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '31',
    brand: 'Mercedes-Benz',
    model: 'G 63 AMG',
    year: 2021,
    mileage: 5300,
    fuel: 'Gasolina',
    priceMLC: 40000,
    priceCUP: null,
    image: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/2021-mercedes-amg-g63-mmp-1-1604077613.jpg?crop=1.00xw:0.750xh;0,0.151xh&resize=1200:*',
    isNew: true,
  },
  {
    id: '32',
    brand: 'BMW',
    model: '525i',
    year: 2003,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 28000,
    priceCUP: null,
    image: 'https://images.classic.com/vehicles/3dafcca293492916b1a9ad3349310d6a16ed0c02.jpg?auto=format&fit=crop&ar=16:9',
    isNew: false,
  },
  {
    id: '33',
    brand: 'BMW',
    model: 'X5',
    year: 2015,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 30000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.40a89045c4413c5292358396858bb44d?rik=sh4voTMQeg31QA&riu=http%3a%2f%2fimages.hgmsites.net%2fhug%2f2015-bmw-x5-series_100487699_h.jpg&ehk=YX3yJDC6nOMGmHyURvivdeDQfpmR518FfzxWgHuCuz0%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '34',
    brand: 'Nissan',
    model: 'Kicks',
    year: 2021,
    mileage: 14300,
    fuel: 'Gasolina',
    priceMLC: 20000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.bd56c2527c7f41a029e2b8cc41156560?rik=VEq%2fjQpCuuAcQg&pid=ImgRaw&r=0',
    isNew: true,
  },
  {
    id: '35',
    brand: 'Peugeot',
    model: '408',
    year: 2015,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 18000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.c6b035f061217eb1e7c4ce0057e0a016?rik=Fn9oDYooDkdO%2bQ&riu=http%3a%2f%2fwww.carsmagazine.com.ar%2fwp-content%2fuploads%2f2015%2f08%2fnuevo-peugeot-408-argentina-1.jpg&ehk=pfi1a%2bUXObjw5aCbVUyBLNrsad3fvSPnVyNN82WAkyI%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '36',
    brand: 'Renault',
    model: 'Sandero',
    year: 2018,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 26000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.81b08ee607c3cb9b64491b5fa89b7954?rik=tkMCRpXKgFs%2fGA&riu=http%3a%2f%2fconduciendo.com%2fwp-content%2fuploads%2f2018%2f09%2fRenaultSanderoStepwayVolcom-07092018-08.jpg&ehk=uWyBAPtkwslHzAF4XJqErh8svA%2fHuYQbIpwXqWvou%2bY%3d&risl=&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '37',
    brand: 'Suzuki',
    model: 'Swift',
    year: 2023,
    mileage: 0,
    fuel: 'Híbrido',
    priceMLC: 25990,
    priceCUP: null,
    image: 'https://www.motorisumotori.it/wp-content/uploads/2022/10/Nuova-Suzuki-Swift-Sport-1122x631.jpg',
    isNew: true,
  },
  {
    id: '38',
    brand: 'Suzuki',
    model: 'Grand Vitara',
    year: 2025,
    mileage: 0,
    fuel: 'Híbrido',
    priceMLC: 31500,
    priceCUP: null,
    image: 'https://media.drive.com.au/obj/tx_q:50,rs:auto:1920:1080:1/driveau/upload/cms/uploads/yrghlnosoxo3qcruoyl1',
    isNew: true,
  },
  {
    id: '39',
    brand: 'Audi',
    model: 'Q7',
    year: 2020,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 75000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/OIP.oqaIjfmFhY3VePFbSldyvAHaE7?rs=1&pid=ImgDetMain',
    isNew: false,
  },
  {
    id: '40',
    brand: 'Audi',
    model: 'Q4 e-tron',
    year: 2024,
    mileage: null,
    fuel: 'Eléctrico',
    priceMLC: 75000,
    priceCUP: null,
    image: 'https://soymotor.com/sites/default/files/imagenes/noticia/audi-q4-e-tron-2021-principal-soymotor.jpg',
    isNew: true,
  },
  {
    id: '41',
    brand: 'Ford',
    model: 'Mustang Mach-E',
    year: 2023,
    mileage: null,
    fuel: 'Eléctrico',
    priceMLC: 31000,
    priceCUP: null,
    image: 'https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/09/ford-mustang-mach-e-15.jpg',
    isNew: true,
  },
  {
    id: '42',
    brand: 'MG (SAIC)',
    model: '5',
    year: 2024,
    mileage: 0,
    fuel: 'Gasolina',
    priceMLC: 37000,
    priceCUP: null,
    image: 'https://images.carexpert.com.au/resize/3000/-/app/uploads/2023/08/2024-MG-5-Essence_MG-5-CAREXPERT-REVIEW-IMAGES_-9.jpeg',
    isNew: true,
  },
  {
    id: '43',
    brand: 'Chevrolet',
    model: 'Aveo',
    year: 2025,
    mileage: 0,
    fuel: 'Gasolina',
    priceMLC: 24500,
    priceCUP: null,
    image: 'https://www.autosactual.mx/wp-content/uploads/2024/09/chevrolet-aveo-2025-mexico-exterior-azul-estacionado.jpg',
    isNew: true,
  },
  {
    id: '44',
    brand: 'Chevrolet',
    model: 'N400',
    year: 2025,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 25000,
    priceCUP: null,
    image: 'https://www.tester.pe/wp-content/uploads/2021/01/aqqqqqq-2048x1268.jpg',
    isNew: true,
  },
  {
    id: '45',
    brand: 'Mitsubishi',
    model: 'Outlander',
    year: 2022,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 25000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.97a2bf30aad402298a81c5bcd13a56a6?rik=CU6rIUOtk93cfQ&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '46',
    brand: 'Volkswagen',
    model: 'Passat',
    year: 2008,
    mileage: null,
    fuel: 'Gasolina',
    priceMLC: 35000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.b1cb0eb6ad10ada8b98e04ac54c48996?rik=DNyjJWQcm5jbQw&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '47',
    brand: 'King Long',
    model: 'Microbús',
    year: 2021,
    mileage: null,
    fuel: 'Diésel',
    priceMLC: 45000,
    priceCUP: null,
    image: 'https://i0.wp.com/versatilemagazine.com.np/wp-content/uploads/2022/09/Screen-Shot-2022-09-18-at-11.05.35-PM.png?fit=1920%2C1310&ssl=1',
    isNew: false,
  },
  {
    id: '48',
    brand: 'Toyota',
    model: 'Sienna Híbrida',
    year: 2021,
    mileage: null,
    fuel: 'Híbrido',
    priceMLC: 67000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.67057564b15bff70aa85cc6827cf2afa?rik=9aeg%2bFJiKP%2f1Qg&pid=ImgRaw&r=0',
    isNew: false,
  },
  {
    id: '49',
    brand: 'Kia',
    model: 'Carnival',
    year: 2023,
    mileage: 170,
    fuel: 'Gasolina',
    priceMLC: 30000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.0cff1a51e672809f4118ab76488c2d7f?rik=eNHvLAYLZhxQ9g&pid=ImgRaw&r=0',
    isNew: true,
  },
  {
    id: '50',
    brand: 'Bestune',
    model: 'T55',
    year: 2024,
    mileage: 8000,
    fuel: 'Gasolina',
    priceMLC: 45000,
    priceCUP: null,
    image: 'https://th.bing.com/th/id/R.35f2965cde17a3d05e8a3d0a911b5645?rik=uZb2ggw9XjNisg&riu=http%3a%2f%2fautoreview.ru%2fimages%2fArticle%2f1754%2fArticle_175442_860_575.jpg&ehk=HZIoZMUT8lqLDDRUgjQPj2zbZaADB5Pm2siSXvIjwAk%3d&risl=&pid=ImgRaw&r=0',
    isNew: true,
  },
];

export interface Accessory {
  id: string;
  name: string;
  price: number;
  images: string[];
  category: string;
  description: string;
}

export const accessories: Accessory[] = [
  {
    id: '1',
    name: 'Tapetes de Goma',
    price: 120,
    images: [
      '/accesorios/tapetes-1.jpg',
      '/accesorios/tapetes-2.jpg',
      '/accesorios/tapetes-3.jpg'
    ],
    category: 'Interior',
    description: 'Tapetes de goma de alta calidad para proteger el interior de tu vehículo. Diseñados para un ajuste perfecto y fácil limpieza.',
  },
  {
    id: '2',
    name: 'Portaequipaje',
    price: 350,
    images: [
      '/accesorios/portaequipaje-1.jpg',
      '/accesorios/portaequipaje-2.jpg'
    ],
    category: 'Exterior',
    description: 'Portaequipaje de aluminio ligero con capacidad para hasta 50kg. Instalación rápida y fácil.',
  },
  {
    id: '3',
    name: 'Sistema de Sonido Premium',
    price: 800,
    images: [
      '/accesorios/sonido-1.jpg',
      '/accesorios/sonido-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Sistema de sonido premium con 6 parlantes, subwoofer y pantalla táctil de 7". Conectividad Bluetooth y USB.',
  },
  {
    id: '4',
    name: 'Asientos de Cuero',
    price: 1200,
    images: [
      '/accesorios/asientos-1.jpg',
      '/accesorios/asientos-2.jpg'
    ],
    category: 'Interior',
    description: 'Asientos de cuero de alta calidad con costuras en contraste. Diseño ergonómico y cómodo.',
  },
  {
    id: '5',
    name: 'Funda de Volante',
    price: 90,
    images: [
      '/accesorios/funda-volante.jpg'
    ],
    category: 'Interior',
    description: 'Funda de volante de cuero sintético con diseño elegante y ajuste perfecto.',
  },
  {
    id: '6',
    name: 'Tapetes de Goma',
    price: 120,
    images: [
      '/accesorios/tapetes-1.jpg',
      '/accesorios/tapetes-2.jpg',
      '/accesorios/tapetes-3.jpg'
    ],
    category: 'Interior',
    description: 'Tapetes de goma de alta calidad para proteger el interior de tu vehículo. Diseñados para un ajuste perfecto y fácil limpieza.',
  },
  {
    id: '7',
    name: 'Portaequipaje',
    price: 350,
    images: [
      '/accesorios/portaequipaje-1.jpg',
      '/accesorios/portaequipaje-2.jpg'
    ],
    category: 'Exterior',
    description: 'Portaequipaje de aluminio ligero con capacidad para hasta 50kg. Instalación rápida y fácil.',
  },
  {
    id: '8',
    name: 'Sistema de Sonido Premium',
    price: 800,
    images: [
      '/accesorios/sonido-1.jpg',
      '/accesorios/sonido-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Sistema de sonido premium con 6 parlantes, subwoofer y pantalla táctil de 7". Conectividad Bluetooth y USB.',
  },
  {
    id: '9',
    name: 'Asientos de Cuero',
    price: 1200,
    images: [
      '/accesorios/asientos-1.jpg',
      '/accesorios/asientos-2.jpg'
    ],
    category: 'Interior',
    description: 'Asientos de cuero de alta calidad con costuras en contraste. Diseño ergonómico y cómodo.',
  },
  {
    id: '10',
    name: 'Funda de Volante',
    price: 90,
    images: [
      '/accesorios/funda-volante.jpg'
    ],
    category: 'Interior',
    description: 'Funda de volante de cuero sintético con diseño elegante y ajuste perfecto.',
  },
  {
    id: '11',
    name: 'Cubreasientos de Tela',
    price: 200,
    images: [
      '/accesorios/cubreasientos-1.jpg',
      '/accesorios/cubreasientos-2.jpg'
    ],
    category: 'Interior',
    description: 'Cubreasientos de tela de alta calidad con diseño elegante y fácil limpieza.',
  },
  {
    id: '12',
    name: 'Organizador de Cajuela',
    price: 150,
    images: [
      '/accesorios/organizador-1.jpg',
      '/accesorios/organizador-2.jpg'
    ],
    category: 'Interior',
    description: 'Organizador de cajuela con compartimentos para herramientas y objetos personales.',
  },
  {
    id: '13',
    name: 'Protector de Tablero',
    price: 180,
    images: [
      '/accesorios/protector-1.jpg',
      '/accesorios/protector-2.jpg'
    ],
    category: 'Interior',
    description: 'Protector de tablero de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '14',
    name: 'Sombrilla para Parabrisas',
    price: 60,
    images: [
      '/accesorios/sombrilla-1.jpg',
      '/accesorios/sombrilla-2.jpg'
    ],
    category: 'Exterior',
    description: 'Sombrilla para parabrisas de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '15',
    name: 'Cortinas Laterales',
    price: 70,
    images: [
      '/accesorios/cortinas-1.jpg',
      '/accesorios/cortinas-2.jpg'
    ],
    category: 'Exterior',
    description: 'Cortinas laterales de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '16',
    name: 'Deflectores de Ventana',
    price: 250,
    images: [
      '/accesorios/deflectores-1.jpg',
      '/accesorios/deflectores-2.jpg'
    ],
    category: 'Exterior',
    description: 'Deflectores de ventana de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '17',
    name: 'Bidón de Combustible',
    price: 40,
    images: [
      '/accesorios/bidon-1.jpg',
      '/accesorios/bidon-2.jpg'
    ],
    category: 'Exterior',
    description: 'Bidón de combustible de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '18',
    name: 'Rieles de Techo',
    price: 350,
    images: [
      '/accesorios/rieles-1.jpg',
      '/accesorios/rieles-2.jpg'
    ],
    category: 'Exterior',
    description: 'Rieles de techo de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '19',
    name: 'Barras Portaequipaje',
    price: 300,
    images: [
      '/accesorios/barras-1.jpg',
      '/accesorios/barras-2.jpg'
    ],
    category: 'Exterior',
    description: 'Barras portaequipaje de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '20',
    name: 'Espejos Retrovisores LED',
    price: 400,
    images: [
      '/accesorios/espejos-1.jpg',
      '/accesorios/espejos-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Espejos retrovisores LED de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '21',
    name: 'Luces LED de Cortesía',
    price: 150,
    images: [
      '/accesorios/luces-1.jpg',
      '/accesorios/luces-2.jpg'
    ],
    category: 'Iluminación',
    description: 'Luces LED de cortesía de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '22',
    name: 'Luces Antiniebla',
    price: 220,
    images: [
      '/accesorios/luces-antiniebla-1.jpg',
      '/accesorios/luces-antiniebla-2.jpg'
    ],
    category: 'Iluminación',
    description: 'Luces antiniebla de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '23',
    name: 'Faro LED Principal',
    price: 500,
    images: [
      '/accesorios/faro-1.jpg',
      '/accesorios/faro-2.jpg'
    ],
    category: 'Iluminación',
    description: 'Faro LED principal de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '24',
    name: 'Bombillas HID',
    price: 450,
    images: [
      '/accesorios/bombillas-1.jpg',
      '/accesorios/bombillas-2.jpg'
    ],
    category: 'Iluminación',
    description: 'Bombillas HID de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '25',
    name: 'Bocinas Traseras',
    price: 300,
    images: [
      '/accesorios/bocinas-1.jpg',
      '/accesorios/bocinas-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Bocinas traseras de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '26',
    name: 'Amplificador de Audio',
    price: 1200,
    images: [
      '/accesorios/amplificador-1.jpg',
      '/accesorios/amplificador-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Amplificador de audio de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '27',
    name: 'Subwoofer',
    price: 700,
    images: [
      '/accesorios/subwoofer-1.jpg',
      '/accesorios/subwoofer-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Subwoofer de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '28',
    name: 'Radio AM/FM Bluetooth',
    price: 400,
    images: [
      '/accesorios/radio-1.jpg',
      '/accesorios/radio-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Radio AM/FM Bluetooth de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '29',
    name: 'Adaptador Bluetooth',
    price: 70,
    images: [
      '/accesorios/adaptador-1.jpg',
      '/accesorios/adaptador-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Adaptador Bluetooth de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '30',
    name: 'Soporte de Celular',
    price: 50,
    images: [
      '/accesorios/soporte-1.jpg',
      '/accesorios/soporte-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Soporte de celular de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '31',
    name: 'Cargador USB Múltiple',
    price: 100,
    images: [
      '/accesorios/cargador-1.jpg',
      '/accesorios/cargador-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Cargador USB múltiple de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '32',
    name: 'Cámara de Reversa',
    price: 800,
    images: [
      '/accesorios/camara-1.jpg',
      '/accesorios/camara-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Cámara de reversa de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '33',
    name: 'Sensores de Estacionamiento',
    price: 600,
    images: [
      '/accesorios/sensores-1.jpg',
      '/accesorios/sensores-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Sensores de estacionamiento de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '34',
    name: 'Sistema de Alarma',
    price: 900,
    images: [
      '/accesorios/alarma-1.jpg',
      '/accesorios/alarma-2.jpg'
    ],
    category: 'Seguridad',
    description: 'Sistema de alarma de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '35',
    name: 'Localizador GPS',
    price: 1000,
    images: [
      '/accesorios/localizador-1.jpg',
      '/accesorios/localizador-2.jpg'
    ],
    category: 'Seguridad',
    description: 'Localizador GPS de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '36',
    name: 'Extintor de Incendios',
    price: 300,
    images: [
      '/accesorios/extintor-1.jpg',
      '/accesorios/extintor-2.jpg'
    ],
    category: 'Seguridad',
    description: 'Extintor de incendios de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '37',
    name: 'Triángulo de Emergencia',
    price: 250,
    images: [
      '/accesorios/triangulo-1.jpg',
      '/accesorios/triangulo-2.jpg'
    ],
    category: 'Seguridad',
    description: 'Triángulo de emergencia de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '38',
    name: 'Botiquín de Primeros Auxilios',
    price: 150,
    images: [
      '/accesorios/botiquin-1.jpg',
      '/accesorios/botiquin-2.jpg'
    ],
    category: 'Seguridad',
    description: 'Botiquín de primeros auxilios de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '39',
    name: 'Gato Hidráulico',
    price: 200,
    images: [
      '/accesorios/gato-1.jpg',
      '/accesorios/gato-2.jpg'
    ],
    category: 'Mecánica',
    description: 'Gato hidráulico de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '40',
    name: 'Llave de Cruz',
    price: 80,
    images: [
      '/accesorios/llave-1.jpg',
      '/accesorios/llave-2.jpg'
    ],
    category: 'Mecánica',
    description: 'Llave de cruz de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '41',
    name: 'Extensión de Cables Batería',
    price: 60,
    images: [
      '/accesorios/extensión-1.jpg',
      '/accesorios/extensión-2.jpg'
    ],
    category: 'Mecánica',
    description: 'Extensión de cables batería de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '42',
    name: 'Batería Externa de Emergencia',
    price: 50,
    images: [
      '/accesorios/batería-1.jpg',
      '/accesorios/batería-2.jpg'
    ],
    category: 'Electrónica',
    description: 'Batería externa de emergencia de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '43',
    name: 'Compresor de Aire Portátil',
    price: 1100,
    images: [
      '/accesorios/compresor-1.jpg',
      '/accesorios/compresor-2.jpg'
    ],
    category: 'Neumáticos',
    description: 'Compresor de aire portátil de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '44',
    name: 'Kit de Reparación de Llantas',
    price: 800,
    images: [
      '/accesorios/kit-1.jpg',
      '/accesorios/kit-2.jpg'
    ],
    category: 'Neumáticos',
    description: 'Kit de reparación de llantas de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '45',
    name: 'Juego de Tapacubos',
    price: 200,
    images: [
      '/accesorios/tapacubos-1.jpg',
      '/accesorios/tapacubos-2.jpg'
    ],
    category: 'Rines',
    description: 'Juego de tapacubos de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '46',
    name: 'Rines de Aleación 17"',
    price: 1500,
    images: [
      '/accesorios/rines-1.jpg',
      '/accesorios/rines-2.jpg'
    ],
    category: 'Rines',
    description: 'Rines de aleación 17" de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '47',
    name: 'Rines Deportivos 18"',
    price: 1800,
    images: [
      '/accesorios/rines-deportivos-1.jpg',
      '/accesorios/rines-deportivos-2.jpg'
    ],
    category: 'Rines',
    description: 'Rines deportivos 18" de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '48',
    name: 'Kit de Limpieza Exterior',
    price: 300,
    images: [
      '/accesorios/kit-limpieza-1.jpg',
      '/accesorios/kit-limpieza-2.jpg'
    ],
    category: 'Limpieza',
    description: 'Kit de limpieza exterior de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '49',
    name: 'Kit de Limpieza Interior',
    price: 200,
    images: [
      '/accesorios/kit-limpieza-interior-1.jpg',
      '/accesorios/kit-limpieza-interior-2.jpg'
    ],
    category: 'Limpieza',
    description: 'Kit de limpieza interior de alta calidad para proteger el interior de tu vehículo.',
  },
  {
    id: '50',
    name: 'Cera Automotriz Líquida',
    price: 250,
    images: [
      '/accesorios/cera-1.jpg',
      '/accesorios/cera-2.jpg'
    ],
    category: 'Limpieza',
    description: 'Cera automotriz líquida de alta calidad para proteger el interior de tu vehículo.',
  },
];

export const services = [
  {
    id: 'reparacion',
    title: 'Reparación y Mantenimiento',
    description:
      'Servicio completo de reparación y mantenimiento para todas las marcas y modelos de vehículos.',
    icon: <Wrench className='h-6 w-6' />,
  },
  {
    id: 'asesoria',
    title: 'Asesoría Técnica',
    description:
      'Asesoramiento profesional para la compra, venta o mantenimiento de tu vehículo.',
    icon: <Tool className='h-6 w-6' />,
  },
  {
    id: 'piezas',
    title: 'Venta de Piezas y Accesorios',
    description:
      'Amplio catálogo de piezas originales y accesorios para personalizar tu vehículo.',
    icon: <ShoppingCart className='h-6 w-6' />,
  },
];
